# Generated by Django 4.2.2 on 2023-08-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'advertisement'},
        ),
    ]
